IMAGE_NAME = "geerlingguy/ubuntu1804"

Vagrant.configure("2") do |config|
  vagrant_root = File.dirname(__FILE__)

  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  # https://www.strongswan.org/testing/testresults/ikev1/net2net-psk/index.html

  config.vm.define "alice" do |node|
    node.vm.box = IMAGE_NAME
    node.vm.network "private_network", ip: "10.1.0.10", netmask: "255.255.255.0"
    node.vm.hostname = "alice"
  end

  config.vm.define "moon" do |node|
    node.vm.box = IMAGE_NAME
    node.vm.network "private_network", ip: "10.1.0.11", netmask: "255.255.255.0"
    node.vm.network "private_network", ip: "192.168.0.11", netmask: "255.255.255.0"
    node.vm.hostname = "moon"
  end

  config.vm.define "sun" do |node|
    node.vm.box = IMAGE_NAME
    node.vm.network "private_network", ip: "10.2.0.11", netmask: "255.255.255.0"
    node.vm.network "private_network", ip: "192.168.0.22", netmask: "255.255.255.0"
    node.vm.hostname = "sun"
  end

  config.vm.define "bob" do |node|
    node.vm.box = IMAGE_NAME
    node.vm.network "private_network", ip: "10.2.0.10", netmask: "255.255.255.0"
    node.vm.hostname = "bob"
  end

end
